name: Output Issues
on: [issues, workflow_dispatch]
jobs:
    output: 
        runs-on: ubuntu-latest
        steps:
            - name: Output any Context Metadata
              run: echo "${{toJSON(github)}}"